-- AlterTable
ALTER TABLE "Tour" ADD COLUMN     "availableDates" TEXT,
ADD COLUMN     "bestFor" TEXT,
ADD COLUMN     "bookingDeadline" TIMESTAMP(3),
ADD COLUMN     "bookingPolicies" TEXT,
ADD COLUMN     "cancellationTerms" TEXT,
ADD COLUMN     "canonicalUrl" TEXT,
ADD COLUMN     "categoryId" TEXT,
ADD COLUMN     "citiesCovered" TEXT,
ADD COLUMN     "currency" TEXT DEFAULT 'INR',
ADD COLUMN     "customizationOptions" TEXT,
ADD COLUMN     "destinationCountry" TEXT,
ADD COLUMN     "destinationState" TEXT,
ADD COLUMN     "difficultyLevel" TEXT,
ADD COLUMN     "durationDays" INTEGER,
ADD COLUMN     "durationNights" INTEGER,
ADD COLUMN     "featuredImage" TEXT,
ADD COLUMN     "groupSizeMax" INTEGER,
ADD COLUMN     "groupSizeMin" INTEGER,
ADD COLUMN     "highlights" TEXT,
ADD COLUMN     "hotelCategories" TEXT,
ADD COLUMN     "images" TEXT,
ADD COLUMN     "maximumTravelers" INTEGER,
ADD COLUMN     "metaKeywords" TEXT,
ADD COLUMN     "minimumTravelers" INTEGER,
ADD COLUMN     "ogDescription" TEXT,
ADD COLUMN     "ogImage" TEXT,
ADD COLUMN     "ogTitle" TEXT,
ADD COLUMN     "originalPrice" INTEGER,
ADD COLUMN     "packageType" TEXT,
ADD COLUMN     "primaryDestination" TEXT,
ADD COLUMN     "region" TEXT,
ADD COLUMN     "regionTags" TEXT,
ADD COLUMN     "seasonalPricing" TEXT,
ADD COLUMN     "shortDescription" TEXT,
ADD COLUMN     "status" TEXT DEFAULT 'active',
ADD COLUMN     "themes" TEXT,
ADD COLUMN     "tourSubType" TEXT,
ADD COLUMN     "tourType" TEXT,
ADD COLUMN     "twitterDescription" TEXT,
ADD COLUMN     "twitterImage" TEXT,
ADD COLUMN     "twitterTitle" TEXT;

